from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    args = [
        DeclareLaunchArgument('drone_num', default_value='4'),
        DeclareLaunchArgument('map_source_type', default_value='pointcloud'),
        DeclareLaunchArgument('map_topic', default_value='/swarm_exploration/occupancy_grid'),
        DeclareLaunchArgument('odom_topic_prefix', default_value='/drone_'),
        DeclareLaunchArgument('odom_topic_suffix', default_value='visual_slam/odom'),
        DeclareLaunchArgument('pointcloud_map_topic', default_value='/map_generator/global_cloud'),
        DeclareLaunchArgument('local_cloud_topic_suffix', default_value='pcl_render_node/cloud'),
        DeclareLaunchArgument(
            'grid_cloud_topic_suffix',
            default_value='grid/grid_map/occupancy_inflate'),
        DeclareLaunchArgument(
            'occupancy_grid_topic',
            default_value='/swarm_exploration/occupancy_grid'),
        DeclareLaunchArgument('map_source_resolution', default_value='0.1'),
        DeclareLaunchArgument('sensing_radius', default_value='5.0'),
        DeclareLaunchArgument('occupied_min_z', default_value='0.05'),
        DeclareLaunchArgument('occupied_max_z', default_value='5.0'),
        DeclareLaunchArgument('frame_id', default_value='world'),
        DeclareLaunchArgument('map_size_x', default_value='36.0'),
        DeclareLaunchArgument('map_size_y', default_value='20.0'),
        DeclareLaunchArgument('map_size_z', default_value='5.0'),
        DeclareLaunchArgument('enable_racer_visualizer', default_value='true'),
        DeclareLaunchArgument('publish_explored_cloud', default_value='true'),
        DeclareLaunchArgument('publish_occupied_cloud', default_value='true'),
        DeclareLaunchArgument('publish_unknown_cloud', default_value='true'),
        DeclareLaunchArgument('visualization_period', default_value='0.5'),
        DeclareLaunchArgument('visualization_z', default_value='0.05'),
        DeclareLaunchArgument('occupied_threshold', default_value='50'),
        DeclareLaunchArgument('free_value', default_value='0'),
        DeclareLaunchArgument('unknown_value', default_value='-1'),
        DeclareLaunchArgument('unknown_downsample', default_value='2'),
        DeclareLaunchArgument('explored_downsample', default_value='1'),
        DeclareLaunchArgument('occupied_downsample', default_value='1'),
        DeclareLaunchArgument(
            'enable_multi_drone_separation',
            default_value='true',
            description='Enable unique and separated multi-drone exploration goals'),
        DeclareLaunchArgument(
            'enable_hgrid',
            default_value='true',
            description='Enable HGrid region allocation'),
        DeclareLaunchArgument(
            'enable_role_assignment',
            default_value='true',
            description='Enable automatic explorer and garbage-collector roles'),
    ]

    node = Node(
        package='exploration_swarm',
        executable='swarm_exploration_node',
        name='swarm_exploration_node',
        output='screen',
        parameters=[{
            'drone_num': LaunchConfiguration('drone_num'),
            'map_source_type': LaunchConfiguration('map_source_type'),
            'map_topic': LaunchConfiguration('map_topic'),
            'odom_topic_prefix': LaunchConfiguration('odom_topic_prefix'),
            'odom_topic_suffix': LaunchConfiguration('odom_topic_suffix'),
            'map_source.cloud_topic': LaunchConfiguration('pointcloud_map_topic'),
            'map_source.local_cloud_topic_suffix': LaunchConfiguration('local_cloud_topic_suffix'),
            'map_source.grid_cloud_topic_suffix': LaunchConfiguration('grid_cloud_topic_suffix'),
            'map_source.occupancy_grid_topic': LaunchConfiguration('occupancy_grid_topic'),
            'map_source.odom_topic_suffix': LaunchConfiguration('odom_topic_suffix'),
            'map_source.resolution': LaunchConfiguration('map_source_resolution'),
            'map_source.sensing_radius': LaunchConfiguration('sensing_radius'),
            'map_source.occupied_min_z': LaunchConfiguration('occupied_min_z'),
            'map_source.occupied_max_z': LaunchConfiguration('occupied_max_z'),
            'frame_id': LaunchConfiguration('frame_id'),
            'map_size_x': LaunchConfiguration('map_size_x'),
            'map_size_y': LaunchConfiguration('map_size_y'),
            'map_size_z': LaunchConfiguration('map_size_z'),
            'map_margin': 1.0,
            'min_z': 0.8,
            'default_goal_z': 1.0,
            'publish_period': 0.5,
            'publish_only_when_reached': True,
            'goal_reached_threshold': 0.8,
            'goal_timeout': 20.0,
            'min_goal_distance': 1.0,
            'max_goal_distance': 100.0,
            'min_goal_separation': 3.0,
            'enable_multi_drone_separation': LaunchConfiguration('enable_multi_drone_separation'),
            'enable_hgrid': LaunchConfiguration('enable_hgrid'),
            'enable_role_assignment': LaunchConfiguration('enable_role_assignment'),
            'communication_range': 100000.0,
            'active_collaboration': True,
            'occupied_threshold': LaunchConfiguration('occupied_threshold'),
            'free_value': LaunchConfiguration('free_value'),
            'unknown_value': LaunchConfiguration('unknown_value'),
            'enable_racer_visualizer': LaunchConfiguration('enable_racer_visualizer'),
            'publish_explored_cloud': LaunchConfiguration('publish_explored_cloud'),
            'publish_occupied_cloud': LaunchConfiguration('publish_occupied_cloud'),
            'publish_unknown_cloud': LaunchConfiguration('publish_unknown_cloud'),
            'visualization_period': LaunchConfiguration('visualization_period'),
            'visualization_z': LaunchConfiguration('visualization_z'),
            'unknown_downsample': LaunchConfiguration('unknown_downsample'),
            'explored_downsample': LaunchConfiguration('explored_downsample'),
            'occupied_downsample': LaunchConfiguration('occupied_downsample'),
            'frontier.cluster_min': 10,
            'frontier.cluster_size_xy': 2.0,
            'frontier.cluster_size_z': 10.0,
            'frontier.min_candidate_dist': 0.5,
            'frontier.min_candidate_clearance': 0.41,
            'frontier.candidate_dphi': 0.2617993878,
            'frontier.candidate_rnum': 3,
            'frontier.candidate_rmin': 1.0,
            'frontier.candidate_rmax': 1.5,
            'frontier.down_sample': 1,
            'frontier.min_visib_num': 30,
            'frontier.min_view_finish_fraction': 0.2,
            'perception_utils.top_angle': 0.56125,
            'perception_utils.left_angle': 0.69222,
            'perception_utils.right_angle': 0.68901,
            'perception_utils.max_dist': 4.5,
            'perception_utils.vis_dist': 1.0,
            'exploration.refine_local': True,
            'exploration.refined_num': 7,
            'exploration.refined_radius': 5.0,
            'exploration.max_decay': 0.8,
            'exploration.top_view_num': 15,
            'exploration.vm': 1.5,
            'exploration.am': 1.5,
            'exploration.yd': 1.3962634016,
            'exploration.ydd': 1.5707963268,
            'exploration.w_dir': 1.5,
            'exploration.init_plan_num': 2,
            'explorer.ftr_max_distance': 6.0,
            'explorer.max_ang_dist': 0.5235987756,
            'explorer.label_penalty': 0.0,
            'explorer.w_distance': 0.0,
            'explorer.w_direction': 10.0,
            'explorer.w_others': 1.0,
            'explorer.w_previous_goal': 1.0,
            'collab_assigner.dist_range': 15.0,
            'collab_assigner.dist_collision': 5.0,
            'collab_assigner.w_range': 0.7,
            'collab_assigner.w_collision': 0.3,
            'collab_assigner.active': True,
            'partitioning.min_unknown': 4000,
            'partitioning.min_frontier': 100,
            'partitioning.min_free': 3000,
            'partitioning.consistent_cost': -5.0,
            'partitioning.consistent_cost2': 8.0,
            'partitioning.w_unknown': 0.0,
            'partitioning.grid_size': 10.0,
            'partitioning.use_swarm_tf': True,
            'role_assigner.region_size': 8.0,
            'role_assigner.cluster_xy_size': 3.0,
            'role_assigner.min_num_neighbours': 3,
            'role_assigner.min_num_islands': 4,
            'role_assigner.min_num_trails': 1,
            'role_assigner.fixed': False,
            'role_assigner.fix_role': 0,
            'collector.min_dist_collision': 5.0,
            'collector.min_vel': 0.7,
            'collector.label_penalty': 15.0,
            'collector.velocity_factor': 2.0,
            'collector.w_distance': 3.0,
            'collector.w_direction': 1.0,
            'collector.w_others': 1.0,
            'collector.w_previous_goal': 3.0,
            'potential_field.ka': 1.0,
            'potential_field.kr': 1.0,
            'potential_field.d0': 5.0,
            'potential_field.df': 6.0,
            'potential_field.dc': 2.0,
        }],
    )

    return LaunchDescription(args + [node])
